#!/usr/bin/python ../scripts/shcov
function f1 () {
    echo "f1"
}
function f2() {
    echo "f2"
}
f3 () {
    echo "f3"
}
f4() {
    echo "f4"
}
function f5 () (
    echo "f5"
)
function f6() {
    echo "f6"
}
f7 () {
    echo "f7"
}
f8() {
    echo "f8"
}
function f9 () { echo "f9"; }
function f10() { echo "f10"; }
f11 () { echo "f11"; }
f12() { echo "f12"; }
function f13 () ( echo "f13"; )
function f14() { echo "f14"; }
f15 () { echo "f15"; }
f16() { echo "f16"; }
f17()
{ echo "f17"; }
f18()
{
    echo "f18"; }

for x in {1..18}; do
	eval f$x
done

# Instrumented lines: tests + 2
# Executed lines: tests + 2
